-- Q1. What is the total revenue generated by male vs. female customers?

select gender,concat('$ ', format(sum(`purchase_amount_(usd)`),2)) as Total_revenue
from cleaned_campaign_reports
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, discount_applied,`purchase_amount_(usd)`, (select avg(`purchase_amount_(usd)`) from cleaned_campaign_reports) as Average_Purchase 
from cleaned_campaign_reports
where  discount_applied ="Yes"
 and `purchase_amount_(usd)` >= (select avg(`purchase_amount_(usd)`) from cleaned_campaign_reports where discount_applied ="Yes")
limit 10

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased as Prouct,avg(review_rating) as 'Avg_Rating of Product'
from cleaned_campaign_reports
group by item_purchased
order by avg(review_rating) DESC
limit 5

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, avg(`purchase_amount_(usd)`) as Avg_Purchase_Amount
from cleaned_campaign_reports
where shipping_type in ("Standard","Express")
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

SELECT 
    subscription_status,
   avg(`purchase_amount_(usd)`) as Avg_Spend_Amount,
   sum(`purchase_amount_(usd)`) as Toatl_Spend
FROM cleaned_campaign_reports
GROUP BY subscription_status
ORDER BY Avg_Spend_Amount DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?


SELECT 
        item_purchased,
        COUNT(item_purchased)/sum(Count(item_purchased))over() AS Avg_Purchase
FROM cleaned_campaign_reports
WHERE discount_applied = 'Yes'
GROUP BY item_purchased
order by Avg_Purchase desc
limit 5

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with required_data as(
select customer_id,previous_purchases ,
case
when previous_purchases <10 then "New" 
when previous_purchases between 10 and 25 then "Returning"
else "Loyal" End as segment

from cleaned_campaign_reports)

select segment, format(sum(previous_purchases),2) as total_time_purchased ,count(segment)
from required_data
group by segment

-- Q8. What are the top 3 most purchased products within each category? 

with require_data as (
select item_purchased, category, row_number()over(partition by category order by `purchase_amount_(usd)`) as rank_prod
from cleaned_campaign_reports)
select item_purchased,category,rank_prod
from require_data
where rank_prod < 4

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

WITH customer_segments AS (
    SELECT 
        -- 1. Segment customers into Repeat Buyers vs Non-Repeat Buyers
        CASE 
            WHEN previous_purchases > 5 THEN 'Repeat Buyer (>5 Purchases)'
            ELSE 'Casual Buyer (<=5 Purchases)'
        -- 2. Standardise the subscriber flag to 1 (Yes) or 0 (No)
        END AS customer_segment,
        CASE 
            WHEN subscription_status IN ('Yes', 'Y', '1', 1, 'True', 'true') THEN 1
            ELSE 0
        END AS is_sub_numeric
    FROM cleaned_campaign_reports
)
SELECT 
    customer_segment,
    COUNT(*) AS total_customers,
    SUM(is_sub_numeric) AS total_subscribers,
    -- 3. Calculate the percentage of subscribers in each group
    ROUND((SUM(is_sub_numeric) / COUNT(*)) * 100, 2) AS subscription_rate_percentage
FROM customer_segments
GROUP BY customer_segment;


-- Q10. What is the revenue contribution of each age group?

WITH total_revenue AS (
    -- 1. Get the grand total revenue of the entire dataset
    SELECT SUM(`purchase_amount_(usd)`) AS grand_total 
    FROM cleaned_campaign_reports
)
SELECT 
    e.age_group, 
    -- 2. Divide each group's sum by the grand total
    (SUM(e.`purchase_amount_(usd)`) / t.grand_total) * 100 AS percentage_of_grand_total
FROM cleaned_campaign_reports e
CROSS JOIN total_revenue t -- Allows every row to access the grand total
where age_group is not null
GROUP BY e.age_group, t.grand_total;

